name: monitoring-ci

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  lint-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # promtool via Docker (no install on runner needed)
      - name: promtool check config
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE":/work prom/prometheus:latest \
            promtool check config /work/relics/prometheus/prometheus.yml

      - name: promtool check rules
        run: |
          docker run --rm -v "$GITHUB_WORKSPACE":/work prom/prometheus:latest \
            sh -lc 'for f in /work/relics/prometheus/rules/*.yml /work/relics/prometheus/rules/*.yaml 2>/dev/null; do [ -f "$f" ] && promtool check rules "$f"; done'

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: sudo pip install yamllint
      - name: Run yamllint (prom & grafana provisioning)
        run: |
          yamllint -s relics/prometheus/**/*.yml grafana/provisioning/**/*.yaml
