name: monitoring-ci

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-prometheus:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # promtool via Docker (override entrypoint)
      - name: promtool check config
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/work \
            --entrypoint /bin/promtool \
            prom/prometheus:latest \
            check config /work/relics/prometheus/prometheus.yml

      - name: promtool check rules
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE":/work \
            --entrypoint /bin/promtool \
            prom/prometheus:latest \
            sh -lc 'set -e; shopt -s nullglob; for f in /work/relics/prometheus/rules/*.yml /work/relics/prometheus/rules/*.yaml; do echo "→ checking $f"; promtool check rules "$f"; done'

  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: sudo pip install yamllint

      # Relax lint so we catch *syntax* issues but don't bikeshed style
      - name: Run yamllint (prom & grafana provisioning)
        # Set to 'true' to keep the build green even if style issues are found
        continue-on-error: true
        run: |
          yamllint \
            -d "{extends: default, rules: {line-length: disable, truthy: disable, document-start: disable}}" \
            -s \
            relics/prometheus/**/*.yml \
            grafana/provisioning/**/*.yaml
