name: Secret scan

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read          # 👈 required by the sarif uploader
  security-events: write # 👈 required to upload to Code Scanning

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Install gitleaks
        run: |
          ver="8.24.3"
          curl -sSL "https://github.com/gitleaks/gitleaks/releases/download/v${ver}/gitleaks_${ver}_linux_x64.tar.gz" | tar -xz
          sudo mv gitleaks /usr/local/bin/gitleaks
          gitleaks version

      - name: Run gitleaks (use repo config)
        run: |
          gitleaks detect \
            --no-banner \
            --redact \
            --config .github/gitleaks.toml \
            --report-format sarif \
            --report-path gitleaks.sarif
        continue-on-error: true

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
