name: Secret scan (Gitleaks)

on:
  push:
    branches: [ "**" ]
  pull_request:

permissions:
  contents: read
  security-events: write   # <-- needed to upload SARIF to Code Scanning

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --no-banner --redact --report-format sarif --report-path gitleaks.sarif

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
